name: flutter_bluetooth_serial_example
description: "Demonstrates how to use the flutter_bluetooth_serial plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  flutter_bluetooth_serial:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

